name: Package publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: 'self-hosted'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-versuib: 9.0.x
          
      - name: Restore dependencies
        run:  dotnet restore CodigoFacilitoNuget.sln
        
      - name: Build
        run: dotnet build CodigoFacilitoNuget.sln --no-restore -c Release
        
      - name: Pack
        run: dotnet pack CodigoFacilitoNuget.sln -c Release -o nuget
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: nuget-packages
          path: nuget
      

  deploy:
    runs-on: 'self-hosted'
    needs: build
    steps:
      - name: Download Nuget package
        uses: actions/download-artifact@v4.3.0
        with:
          name: nuget-packages
      - name: Push
        run: |
          dotnet  nuget push "CodigoFacilitoNuget.*.nupkg" --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{secrets.GITHUB_TOKEN}}
  
